Issue-131: add bookie pods annotation
pravega/bookkeeper-operator pull request #138
Opened 2021-05-07 11:09 UTC by realAaronWu

### Change log description

add annoation field in bookkeeeper crd and attach annotation to bookie pods and sts

### Purpose of the change

Issue-131

### What the code does
add annoation field in bookkeeeper crd and attach annotation to bookie pods and sts

### How to verify it
set bookie pods annoation via chart values and deploy bookkeeper with the built operator. kubectl describe bookie pods to see if the specified annotation is there.

2021-05-07 15:58 UTC, medvedevigorek commented
@realAaronWu / @anishakj can you please sync up together as it seems you have been working on the same changes? Thanks

2021-05-07 17:06 UTC, anishakj requested changes
Please add unit tests to increase coverage

2021-05-07 17:06 UTC, anishakj commented on pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go
Could you please initialize annotation map in withDefaults function

2021-05-08 02:27 UTC, realAaronWu commented
> @realAaronWu / @anishakj can you please sync up together as it seems you have been working on the same changes? Thanks

We have synced up yesterday, Anisha will provide annotation support for pravega.

2021-05-08 12:15 UTC, anishakj approved these changes
LGTM

2021-05-08 12:16 UTC, merged