Initial changes for controller runtime upgrade
pravega/bookkeeper-operator pull request #72
Opened 2020-09-04 08:39 UTC by anishakj

Signed-off-by: anisha.kj <anisha.kj@dell.com>

### Change log description

Update controller run time to 0.5.2 and operator-sdk to v0.17.0
### Purpose of the change

Fixes #69

### What the code does

With controller run time upgrade, webhook validation mechanism changes. We have to create webhook svc, Also for validation a certificate needs to be installed.

### How to verify it

_(Steps to verify that the changes are effective)_

2020-09-13 17:50 UTC, Prabhaker24 approved these changes
Just add the "how to verify" section in the PR description other than that this PR LGTM.

2020-09-14 09:39 UTC, SrishT requested changes

2020-09-14 09:39 UTC, SrishT commented on doc/operator-upgrade.md
> +To manually trigger the upgrade to Operator 0.1.3, run the script `operatorUpgrade.sh` under [tools](https://github.com/pravega/bookkeeper-operator/blob/master/tools) folder. This script patches the
This script patches the ?

2020-09-14 10:28 UTC, anishakj commented on tools/operatorUpgrade.sh
> +UpgradingToBookkeeperoperator $1 $2 $3
Done

2020-09-14 10:28 UTC, anishakj commented on tools/manifest_files/patch.yaml
> +        image: kjanisha/bookkeeper-operator:openapi
Done

2020-09-14 10:28 UTC, anishakj commented on doc/operator-upgrade.md
> +To manually trigger the upgrade to Operator 0.1.3, run the script `operatorUpgrade.sh` under [tools](https://github.com/pravega/bookkeeper-operator/blob/master/tools) folder. This script patches the
Done

2020-09-14 10:53 UTC, SrishT approved these changes
LGTM

2020-09-14 13:04 UTC, merged